version: "3.8"
services:
  testing:
    build: .
    tty: true
    volumes:
      - .:/code
    command: npm run test -- --watch
  serving:
    build: .
    volumes:
      - .:/code
    command: python3 -m http.server
  
